FROM python:3.12-slim

# Установка зависимостей
RUN pip install --no-cache-dir requests

# Рабочая директория
WORKDIR /

# Копирование скрипта
COPY matryoshka_bot.py /bot.py

# Запуск бота
CMD ["python3", "/bot.py"]
